### ISSUE TITLE
Error  with cordova-ios version 5+

### ISSUE THREAD

**Issue by sivastyle** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#150]
When I build using ios, got error as like firebase.h  . I went ahead and made lot of changes like installing firebase using pod,  Even if we install pod firebase/core, firebase/messaging it leads to some other subsequent error with and  $(inherited) for linker flags as well didn't helped.  After trying 2 days moved on to another plugin (Looks like issue is only with cordova-oios 5.X versions.

 CompileC /var/root/Library/Developer/Xcode/DerivedData/PROJNAME-fflckxrcmiqwasgblfazxcjgkvkp/Build/Intermediates.noindex/PROJNAME.build/Debug-iphonesimulator/PROJNAME.build/Objects-normal/x86_64/FCMPlugin.o /Users/vsonline/REM/rem/remApp/platforms/ios/REM/Plugins/cordova-plugin-fcm-with-dependecy-updated/FCMPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
(node:8070) UnhandledPromiseRejectionWarning: Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/vsonline/REM/rem/remApp/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:8070) UnhandledPromiseRejectionWarning: Unhandled promise reje

**Comment by andrehtissot** [comment]
Would you share your package.json? Or even better, provide a github repo that I can use to debug?

**Comment by DaedalusAB** [comment]
Hi, I had the same issue. Solved it by editing plugin.xml like this (old is commented):

`
		
		

		<framework src="Firebase/Core" type="podspec" spec=">= 6.21.0"/>
        <framework src="Firebase/Analytics" type="podspec" spec=">= 6.21.0"/>
       	<framework src="Firebase/Messaging" type="podspec" spec=">= 6.21.0"/>`

@andrehtissot Why is Firebase/Core not listed in plugin.xml ? 
ps. This is iOS only.

**Comment by sivastyle** [comment]
Thanks, Will try the same. For now I switched to another plugin and will get back to this at later point. Looks like above should fix the issue.

**Comment by andrehtissot** [comment]
@DaedalusAB 
It was a dependency of Firebase/Messaging, and, thus, implicitly required.

The <podspec> seems too dependent on cordova version. Thank you @DaedalusAB for pointing it out.

**Comment by andrehtissot** [comment]
Unfortunately, the "<podspec>" configuration is not accepted by cordova (main globally-installed package) versions older than 9. But, if we bring this older "<framework type='podspec'>", then it conflicts with the cordova-ios@5 validations.
As there is no clear way to make an adjustment for this specific case without bringing warnings for everybody. The solution would be to request users to, at least, have cordova@8, and ideally the current one:
```bash
npm install -g cordova@latest
```

**Comment by DaedalusAB** [comment]
Hi @andrehtissot Could you elaborate please (sorry I don't get it)? What is not accepted exactly?

**Comment by mayur-bhandari** [comment]
@andrehtissot I am using Cordova 10.0 but still facing the exact same error.
